### ISSUE TITLE
Request for Experiment Hyperparameters

### ISSUE THREAD

**Issue by HungerPWAY** [Clin0212/HydraLoRA#2]
Subject: Request for Experiment Hyperparameters

Hi Chunlin,

I hope you're doing well.

To better understand and replicate your results, could you please share the hyperparameters used in your experiments? 

Thanks a lot!

Best,
Pengwei

**Comment by Clin0212** [comment]
Hi Pengwei,

Thank you for your interest in our work.

Regarding the hyperparameters, most were set to their default values in our experiments. Specifically, here are the settings we used (per_device_train_batch_size: 1, gradient_accumulation_steps: 8, per_device_eval_batch_size: 1, max_seq_length: 1024) unless noted otherwise in individual scripts. 

I have not modified these values except for the rank, but due to the large number of experiments, I haven't compiled detailed documentation for each specific script. I hope this helps you replicate the results. Please let me know if you need more information.

Best regards, 

Chunlin
