### ISSUE TITLE
About inference phase

### ISSUE THREAD

**Issue by chenyou203** [Clin0212/HydraLoRA#3]
During the inference phase, how did you merge the original parameters with the parameters obtained from HydraLoRA?

**Comment by Clin0212** [comment]
We replace the original LoRA class ([`peft`](https://github.com/Clin0212/HydraLoRA/tree/main/HydraLoRA/peft)) with a new architecture, allowing for direct inference using the modified and fine-tuned LoRA.

**Comment by Hjh233** [comment]
Thanks for your brilliant work!
Since I have trouble running the fine-tune.sh script, I don't know how the trained parameters of LoRA_A, LoRA-Bs and LoRA_route are stored.
I wonder if all the trained parameters are stored in a folder like 'peft_param_path'.
Additionally, for the inference phase, I would like to confirm if the following steps are correct:
1. Add the current directory containing the modified peft and transformers libraries to the Python path:
```
import sys
sys.path.insert(0, 'path_to_your_current_dir_containing_changed_peft&transformers')
```
2. Configure the model as follows:
```
models = [
    dict(
        type=HuggingFaceCausalLM,
        abbr='',
        path="path_to_base_model",
        tokenizer_path='path_to_tokenizer',
        peft_path='peft_param_path',
        ...
    )
]
```
By following these steps, will the model generate results using HydraLoRA via the learned LoRA_A, LoRA_Bs and the LoRA-route parameters during the forward process?
Also, will this setup allow me to obtain the evaluation results using OpenCompass?
Thank you in advance for your help!
