### ISSUE TITLE
A little qs for Figure 3 in Paper and CODE

### ISSUE THREAD

**Issue by Xiaoni-61** [Clin0212/HydraLoRA#9]
Hello, author,

Thank you for your great work and for sharing the code so I can compare and learn.

In Figure 3 in Paper, you use **lora** on the Q V matrix to get this paper motivation, but in code, use **lora** on the three matrix of FFM, i don't know why doing this. I wouldn't appreciate it if you could help me out.

**Comment by Clin0212** [comment]
Thanks for your question. Figure 3 aims to highlight the asymmetry between the A and B modules in LoRA. This asymmetry is common to both the attention and FFN layers due to the different initialization modes.

As for why multiple B modules are used in the FFN layer in the code, this choice is inspired by the design of MoE architectures, where FFN layers are commonly chosen to deploy multiple expert modules (FFN layers typically have larger parameter spaces and offer greater flexibility for task-specific adaptation). However, there is also emerging work exploring MoA (mixture-of-attention) approaches.

**Comment by Xiaoni-61** [comment]
Thank you very much. That's a great solution to my problem
